### ISSUE TITLE
Discord Connector is not inviting members.

### ISSUE THREAD

**Issue by samsoliman** [warlof/seat-discord-connector#37] opened 2019-03-13 03:29 UTC
Discord Connector is not inviting members to discord when they click on join server. Is that by Design or a problem I am running into? 

If it is by design is it possible to modify to invite members to the server when they click join server? and How?

**Comment by warlof** [comment] 2019-03-13 18:32
Hi, 

Users will be invited to the server with the join server button except if they're not accepting the discord prompt. 

Either this or you don't have properly setup the plugin.

**Comment by Pr3ciseD34th** [comment] 2019-03-29 22:46
Im running into the same issue with this. The useres are not getting invited. Can you help with this?

**Comment by warlof** [comment] 2019-05-17 06:45
Hi,

The 400 is a know issue.
Thanks to discord team who push breaking changes on their latest live api.

However, it has break restcord library which is used to talk with Discord.
There is some patch which can be apply manually for now restcord/restcord#83

**Comment by dstevens79** [comment] 2019-05-17 08:14
how do you apply this manually?

**Comment by H4Z4RD-H42** [comment] 2019-05-17 16:53
Please release a official fix, i tried to perform a manul fix without success. My discord bot not invite members but most important for me is that the botnot add/remove roles.

Thanks.

**Comment by warlof** [comment] 2019-05-17 17:31
@H4Z4RD-H42 I plan to make some testing this week-end with the dev branch of the used library.
You also can contribute and try to find a solution that you're sharing with the other ?

**Closed** 2019-05-17 22:51 UTC

**Comment by dstevens79** [comment] 2019-05-17 23:49
"minimum-stability": "dev",
  "prefer-stable": true,

this is required to get that working

**Comment by warlof** [comment] 2019-05-18 07:17
https://github.com/warlof/seat-discord-connector/blob/b5afadc8df051718310b9a669bcc92f3d9f793ea/composer.json#L23 it is tee case?

**Comment by H4Z4RD-H42** [comment] 2019-06-12 00:57
I'm sorry if i'm repetitive but i still have the problem, and there are a little confusion between issues. There are 3 problems from what i can see on github:

1. Installing problem relatee to plugin version. 
2. Discord Connector not inviting users. 
3. Bot not update members roles in discord. 

I have the issue 1 and 3. Issue number 1 solved by installing Restcord but i still have issue number 3 (issue 2 i never had). 

A user opened a topic here some time ago (#43) for issue number 3 but @Warlof redirect the user to this topic (#37) but the problem is different! 

I hope I was clear and I apologize for my english. Thanks!

**Comment by warlof** [comment] 2019-06-12 05:57
@Hazard-H42 problems 2 and 3 are due to the same thing which is the reason why I'm merging issues. It has been fixed inside a 3rd party library version which is not yet available on stable branch and used since v3.2

So both problems are fixed since 3.2

Regarding the first point, directives has been provided into the issue #45
