### ISSUE TITLE
Menu items missing after seat update

### ISSUE THREAD

**Issue by geedon** [warlof/seat-discord-connector#23] opened 2018-09-27 14:50 UTC
Hi, so all my corp member's used to be able to see the discord connector and its been working OK until I updated seat from v3.0.3 to v3.0.8.  On doing so the connector menu items disappeared for everyone unless I have specifically added a group association. If I have the group association, say, where I have a list of officers, it appears and works fine. But I need it to be available to all without manually adding a name.

It is my belief that the following under access management should show it (ignore the fact I've added admin options also as I'm just making a point).

[Image of roles for all corp members](https://imgur.com/a/pusrcHP)

Can you tell me why the menu items are not showing for normal corp members?

Many thanks in advance!

p.s. I notice that the table affiliation_role is empty. How does this even get filled? does it need to be?

**Comment by warlof** [comment] 2018-09-27 17:01
Hi,

About the issue itself, it's a duplicate of warlof/seat-discord-connector#22

Related to your role, affiliation can't work with global scope (related to other permissions than those starting with either `character` or `corporation`)

Furthermore, since you have nobody attached to the role, that just mean it will never provide access to anyone. 

In case you want some autogrouping system, I recommand you to put an eye on https://github.com/herpaderpaldent/seat-groups

**Closed by warlof** 2018-09-27 17:01 UTC

**Comment by geedon** [comment] 2018-09-27 17:40
awesome it appears to work! thanks!
