### ISSUE TITLE
Problem installing 

### ISSUE THREAD

**Issue by Jammersonthe3rd** [warlof/seat-discord-connector#46] opened 2019-05-21 02:43 UTC
After installing seat and getting it all working i started installing plugins with the latest version of seat and i am now getting this error when i try to install:

The command --> composer require warlof/seat-discord-connector
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^3.2 for warlof/seat-discord-connector
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for warlof/seat-discord-connector ^3.2 -> satisfiable by warlof/seat-discord-connector[3.2.0].
    - warlof/seat-discord-connector 3.2.0 requires restcord/restcord dev-develop -> satisfiable by restcord/restcord[dev-develop] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

Any help would be great :)

**Comment by warlof** [comment] 2019-05-21 09:18
Hi, closing this as it's a duplicate of #45.

**Closed by warlof** 2019-05-21 09:18 UTC
